FROM golang:alpine as builder

# Build golang 'dep'
RUN apk update && apk add --no-cache git

WORKDIR $GOPATH/src/go_microservice/consignment-cli

COPY . .


# Manually get all dependencies
RUN go get -u github.com/golang/dep/cmd/dep
RUN go get -u github.com/micro/go-micro
RUN go get -u github.com/lukeecrane/shippy/consignment-service/proto/consignment
RUN go get -u github.com/micro/go-micro/cmd
RUN go get -u  golang.org/x/net/context
# Using go get.
#RUN go mod download


# Build the binary.
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .


############################
# STEP 2 build a small image
############################
FROM alpine:latest

RUN apk --no-cache add ca-certificates

RUN mkdir -p /app
WORKDIR /app

ADD consignment.json /app/consignment.json
COPY --from=builder $GOPATH/src/go_microservice/consignment-cli/consignment-cli .

CMD ["./consignment-cli"]